library(shiny)

shinyUI(pageWithSidebar(
                        headerPanel("RAPPOR Simulation"),
                        sidebarPanel(
                                     tabsetPanel(
                                                 tabPanel("RAPPOR",
                                                          selectInput("size", "Bloom filter size:",
                                                                      c(4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096),
                                                                      selected = 128),
                                                          selectInput("hashes", "Number of hash functions:",
                                                                      c(1, 2, 4, 8, 16, 32),
                                                                      selected = 2),
                                                          selectInput("instances", "Number of cohorts:",
                                                                      c(1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024),
                                                                      selected = 8),
                                                          br(),
                                                          br(),
                                                          sliderInput("N", "Number of samples to generate:",
                                                                      min = 100000, max = 10000000,
                                                                      value = 1000000, step = 100000),
                                                          br(),
                                                          helpText(actionButton("sample", "Rerun Simulations"), align = "center"),
                                                          br(),
                                                          br(),
                                                          helpText("Version 0.1", align = "center"),
                                                          helpText(a("RAPPOR Repository", href="http://github.com/google/rappor"), align = "center")),
                                                 tabPanel("Privacy",
                                                          sliderInput("p", "Probability of reporting noise (p):",
                                                                      min = .01, max = .99, value = .5, step = .01),
                                                          sliderInput("q", "Probability of reporting signal (q):",
                                                                      min = .01, max = .99, value = .75, step = .01),
                                                          sliderInput("f", "Probability of lies (f):",
                                                                      min = 0, max = .99, value = .5, step = .01),
                                                          br(),
                                                          htmlOutput("epsilon"),
                                                          br(),
                                                          helpText("* In addition to p, q and f, the number of hash functions (set in the RAPPOR tab) also effects privacy guarantees."),
                                                          br(),
                                                          br(),
                                                          br()
                                                          ),
                                                 tabPanel("Population",
                                                          sliderInput("nsites", "Number of sites:",
                                                                      min = 100, max = 10000, value = 300, step = 100),
                                                          br(),
                                                          sliderInput("nhttps", "Proportion of sites with HTTPS:",
                                                                      min = .1, max = 0.99, value = 0.7, step = .1),
                                                          br(),
                                                          sliderInput("nhsts", "Proportion of HTTPS sites with HSTS:",
                                                                      min = .1, max = 0.99, value = 0.3, step = .1),
                                                          br(),
                                                          sliderInput("nonzero", "Proportion of non-zero strings:",
                                                                      min = 0, max = 0, value = 0, step = .1),
                                                          br(),
                                                          selectInput("decay", "Decay of non-zero strings",
                                                                      c("Linear", "Exponential", "Constant", "Zipf", "Measured"),
                                                                      selected = "Exponential"),
                                                          br(),
                                                          conditionalPanel(condition = "input.decay == 'Exponential'",
                                                                           sliderInput("expo", "Rate of exponential decay",
                                                                                       min = 1, max = 200, value = 10, step = 1)),
                                                          conditionalPanel(condition = "input.decay == 'Exponential'",
                                                                           sliderInput("background", "Frequency of background strings:",
                                                                                       min = 0, max = .2, value = .05, step = .01)),
                                                          br(),
                                                          br(),
                                                          br()
                                                 ),
                                                 tabPanel("Decoding",
                                                          sliderInput("threshold", "Count threshold ",
                                                                      min = 0.001, max = 0.2, value = 0.005, step = 0.001),
                                                          br(),
                                                          sliderInput("missing", "Proportion of non-zero strings missing from decoding:",
                                                                      min = 0, max = 1, value = 0, step = .1),
                                                          br()
                                                          )
                                     )),
                        mainPanel(
                                  tabsetPanel(
                                              tabPanel("Life of a  Report",
                                                       actionButton("new_user", "New Participant"),
                                                       actionButton("new_value", "New Value"),
                                                       actionButton("new_report", "New Report"),
                                                       plotOutput("example", height = "600px")),
                                              tabPanel("Population", plotOutput("probs", height = "600px")),
                                              tabPanel("Results", helpText(h3("Summary")), htmlOutput("pr"), br(), br(), dataTableOutput("tab"), htmlOutput("pr2"), br(), br(), dataTableOutput("tab2")),
                                              tabPanel("True Bits", plotOutput("truth", height = "800px")),
                                              tabPanel("Estimated Bits", plotOutput("ests", height = "800px")),
                                              tabPanel("Estimates vs Truth", plotOutput("ests_truth", height = "600px")),
                                              # tabPanel("Lasso", plotOutput("lasso", height = "600px")),
                                              tabPanel("Residuals", plotOutput("resid", height = "600px"))
                                              )
                                  )
                        ))
